### ISSUE TITLE
Use unicode strings?

### ISSUE THREAD

**Issue by vihu** [dhellmann/smiley#43]
Tried to have a simple demo run with smiley and encountered the following issue, not sure if it's me or smiley.

Here's the traceback:
```
$ smiley run ./demo.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/smiley/local.py", line 44, in _process_data
    self._dispatch_one(the_db, next_data)
  File "/usr/local/lib/python2.7/dist-packages/smiley/local.py", line 57, in _dispatch_one
    the_db.cache_file_for_run(*data)
  File "/usr/local/lib/python2.7/dist-packages/smiley/db.py", line 303, in cache_file_for_run
    'body': body,
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
```

**Comment by dhellmann** [comment]
I'm sure this is a limitation of Smiley -- I likely didn't test with Unicode.

Can you provide a minimal test script that can be run under Smiley to reproduce the error? I don't need your whole app if you can give a simple script. Thanks!

**Comment by vihu** [comment]
Sorry for the delayed response Doug, a bit busy with work...
I will send you a sample script to test out in some time. However, just to let you know, I tried running smiley within a simple ansible environment (dunno if it helps much).
